[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = [
	"pragma: no cover",
	"raise NotImplementedError",
	"if __name__ == .__main__.:",
	"if typing.TYPE_CHECKING:",
]

[tool.mypy]
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
strict_equality = true

[tool.pytest.ini_options]
addopts = "--strict-markers"
pythonpath = "."
testpaths = ["tests"]
xfail_strict = true

[tool.ruff]
select = ["E", "F", "B", "UP", "C4", "I001", "SIM"]
ignore = ["E501"]
target-version = "py39"
